# command line: main.py recognition -c config/st_gcn/KETI/train.yaml

base_lr: 0.1
batch_size: 50
config: config/st_gcn/KETI/train.yaml
debug: false
device:
- 0
- 1
eval_interval: 5
feeder: feeder.feeder.Feeder
ignore_weights: []
log_interval: 10
model: net.st_gcn.Model
model_args:
    edge_importance_weighting: true
    graph_args:
        layout: openpose
        strategy: spatial
    in_channels: 3
    num_class: 20
nesterov: true
num_epoch: 50
num_worker: 2
optimizer: SGD
pavi_log: false
phase: train
print_log: true
save_interval: 10
save_log: true
save_result: false
show_topk:
- 1
- 5
start_epoch: 0
step:
- 20
- 30
- 40
- 50
test_batch_size: 50
test_feeder_args:
    data_path: ./data/KETI/skeleton/val_data.npy
    label_path: ./data/KETI/skeleton/val_label.pkl
train_feeder_args:
    data_path: ./data/KETI/skeleton/data.npy
    label_path: ./data/KETI/skeleton/label.pkl
    random_choose: true
    random_move: true
    window_size: 150
use_gpu: true
weight_decay: 0.0001
weights: null
work_dir: ./work_dir/recognition/KETI/ST_GCN
