base_lr: 0.1
batch_size: 50
device:
- 0
- 1
feeder: feeder.feeder.Feeder
model: net.st_gcn.Model
model_args:
  edge_importance_weighting: true
  graph_args:
    layout: openpose
    strategy: spatial
  in_channels: 3
  num_class: 7
num_epoch: 50
step:
- 20
- 30
- 40
- 50
test_batch_size: 50
test_feeder_args:
  data_path: ./data/KETI/skeleton/test_data.npy
  label_path: ./data/KETI/skeleton/test_label.pkl
train_feeder_args:
  data_path: ./data/KETI/skeleton/data.npy
  label_path: ./data/KETI/skeleton/label.pkl
  random_choose: true
  random_move: true
  window_size: 150
work_dir: ./work_dir/recognition/KETI/ST_GCN
